name: "action-camo-purge"
author: "kevincobain2000"
description: "Locate and purge all images served via camo.githubusercontent.com for the active branch."

branding:
  icon: 'refresh-cw'
  color: 'blue'

runs:
  using: "composite"

  steps:
    - name: Determine current branch
      id: branch-name
      uses: tj-actions/branch-names@v8

    - name: Purge images from camo.githubusercontent.com
      shell: bash
      run: |
        urls=$(curl -sLk "https://github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}/tree/${{ steps.branch-name.outputs.current_branch }}" | grep -Eo "(http|https)://camo.githubusercontent.com[a-zA-Z0-9./?=_%:-]*")
        while IFS= read -r url; do curl -X PURGE "$url"; done <<< "$urls"
